name: cytoflow
channels:
 - cytoflow
 
dependencies:
    - python==3.9.15
    - numpy==1.21.2
    - pandas==1.3.5
    - matplotlib==3.5.0
    - bottleneck==1.3.2
    - numexpr==2.8.1
    - scipy==1.7.3
    - scikit-learn==1.0.1
    - seaborn==0.11.2
    - statsmodels==0.13.0
    - natsort==7.1.1
    - numba==0.56.3

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.2
    - importlib_resources==5.2.0

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - camel==0.1.2
    - yapf==0.30.0
    
    # only install mkl libraries on windows, where they're required
    - nomkl # [not win]

    # - {{compiler('cxx')}}
    - sphinx==4.2.0
    - bleach==3.3.0
    - swig==4.0.2